Q 1.Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [53]:
import numpy as np

In [54]:
def vender_matrix(vector,n,boo):
    a=[]
    if boo == False:
        for i in vector:
            b=[]
            for j in range(n):
                b.append(i**(n-1-j))
            a.append(b)
    else:
        for i in vector:
            b=[]
            for j in range(n):
                b.append(i**j)
            a.append(b)    
    return np.mat(a)    
        


In [55]:
#if value of boo is passed as false it generates G.P in descending order in each row
vector=np.array([1,2,3,5])
result=vender_matrix(vector,len(vector),False)
result

matrix([[  1,   1,   1,   1],
        [  8,   4,   2,   1],
        [ 27,   9,   3,   1],
        [125,  25,   5,   1]])

In [56]:
#if value of boo is passed as false it generates G.P in descending order in each row
result=vender_matrix(vector,len(vector),True)
result


matrix([[  1,   1,   1,   1],
        [  1,   2,   4,   8],
        [  1,   3,   9,  27],
        [  1,   5,  25, 125]])

In [57]:
# n is the len of columns it can be equal  to to len to input vactor to produce any square matrix or it can be any user defined value
n=int(input("Enter the value of N:"))
result=vender_matrix(vector,n,False)
result

Enter the value of N:5


matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [625, 125,  25,   5,   1]])

Q 2.Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [58]:
def arr_avarage(arr,size):
    b=[]
    for i in range(len(arr)-size+1):
        add=0
        for k in range(i,i+size):
            add=add+arr[k]
        avarage=add/size
        b.append(avarage)
            
    return np.array(b)        
    

In [59]:
#with window size=4
arr=np.array([10,20,30,40,50,60,70,80,90,100])
avarage_array=arr_avarage(arr,4)
avarage_array

array([25., 35., 45., 55., 65., 75., 85.])

In [60]:
#with window  size=3
arr=np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
avarage_array=arr_avarage(arr,3)
avarage_array

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])